# ************************************************************分割线************************************************************

server:
  port: 80

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: untitled
      username: root
      password: 2468
      auth: mongodb://root:2468@127.0.0.1:27017/
